export const NOTE_ACTION_TYPE = {
  FETCH_REQUEST: "NOTE_FETCH_REQUEST",
  FETCH_SUCCESS: "NOTE_FETCH_SUCCESS",
  FETCH_FAILURE: "NOTE_FETCH_FAILURE",

  ADD_REQUEST: "NOTE_ADD_REQUEST",
  ADD_SUCCESS: "NOTE_ADD_SUCCESS",
  ADD_FAILURE: "NOTE_ADD_FAILURE",

  DELETE_REQUEST: "NOTE_DELETE_REQUEST",
  DELETE_SUCCESS: "NOTE_DELETE_SUCCESS",
  DELETE_FAILURE: "NOTE_DELETE_FAILURE"
};

export const AUTH_ACTION_TYPE = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE"
}
